### PR TITLE
Adds Mac GUI

### PR DESCRIPTION
**Pull request by qarmin**
Fixes https://github.com/qarmin/czkawka/issues/11
Fixes https://github.com/qarmin/czkawka/issues/64

Thanks to ImplicitEmpiricism I have now basic instructions how to compile Czkawka on MacOS.
```
xcode-select --install
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
brew install rust gtk+3 
curl -L https://github.com/qarmin/czkawka/archive/2.0.0.tar.gz | tar -zxvf -
cd czkawka-2.0.0
cargo run --bin czkawka_gui
```
Let's see if I can wrap it inside Github CI

Test binary - [czkawka_gui-macOS-stable.zip](https://github.com/qarmin/czkawka/files/5751893/czkawka_gui-macOS-stable.zip)

It should be able to run with help of terminal.
Probably after some changes it will be able to run when double clicking at it.

If you could open app, then please print here screenshot with OS info,

### CODE REVIEW

**Comment by magnusviri** [comment]
I'm not sure if you still want screenshots. I'm on 10.14.6. 
Screen Shot 2021-01-04 at 2 45 06 AM

**Comment by qarmin** [comment]
Thanks,
Looks that all icons are missing.
Could you install an icon pack to see if it will restore the icons?

`brew install adwaita-icon-theme`

**Comment by magnusviri** [comment]
I did that and there's no change.

**Comment by renarsvilnis** [comment]
Want to add to @magnusviri, icons also missing for me. `macOS Big Sur 11.3`
image

**Comment by NickKaramoff** [comment]
Weirdly enough, installing `adwaita-icon-theme` resolved the issue for me (as mentioned in #368). I'm running macOS 10.15.7

grafik

**Pull request merged**
