### PR TITLE
Fixing czech translation

### PR DESCRIPTION
**Pull request by habernal**
Just noticed a non-sense translation in the main GUI window.

### CODE REVIEW

**Comment by qarmin** [comment]
Czech translation is computer generated, so such invalid messages are expected

Translations should be changed only in https://crowdin.com/project/czkawka, because it is easier to manage multiple languages at once with it

**Comment by qarmin** [comment]
Thanks!

**Comment by habernal** [comment]
OK, sorry, that wasn't clear to me from the readme.

**Comment by alexislefebvre** [comment]
Yes [this page](https://github.com/qarmin/czkawka/blob/master/instructions/Translations.md#translations) mentions Crowdin and also explanations about the files, we may made it more clear that Crowdin must be used.

**Pull request merged**
