### PR TITLE
Add Italian translation - #251

### PR DESCRIPTION
**Pull request by igor-cali**
Add Italian translation

### CODE REVIEW

**Comment by qarmin** [comment]
PR needs rebase, because I changed how languages are displayed for user - now instead (native name + short name) is (native name (english name)) except of course English.

I also added script `misc/translation_test.py` which will show what strings are missing

**Comment by igor-cali** [comment]
I reviewed the translation.
I can't find the script `misc/translation_test.py`. Maybe it's not merged upstream.
I would like to run it before this PR is merged.

**Comment by qarmin** [comment]
(－‸ლ)
My tool did not not add this file to git, since it was new.
Now it is available - https://github.com/qarmin/czkawka/blob/master/misc/translation_test.py

**Comment by igor-cali** [comment]
The review should be complete now.

**Comment by qarmin** [comment]
Thanks!

**Pull request merged**
