### PR TITLE
README: Allow Snap to access to external drives

### LINKED ISSUE #217: Snap package bugs
- [ ] - External drives are not available
- [ ] - Some folders like `/home/user/.kodi` are not available

Also Gnome-3-34 SDK is broken so I am forced to use Gnome-3-28 SDK.

I will try to drop use of Gnome extension.

### PR DESCRIPTION
**Pull request by alexislefebvre**
Fixes #217

Further explanation: https://askubuntu.com/questions/1054893/gimp-2-10-doesnt-have-permission-to-access-a-usb-drive-why-how-to-resolve-1

### CODE REVIEW

**Comment by alexislefebvre** [comment]
It won't be mandatory after 13fbd9f7c6d925c230dc755f813ecceea2c468a3, feel free to close the PR.

**Comment by qarmin** [comment]
I wait for response in https://forum.snapcraft.io/t/request-classic-confinement-for-czkawka/22200.
If request will be rejected, I will revert my previous commits.

**Comment by alexislefebvre** [comment]
You had an answer. :slightly_smiling_face:

**Comment by qarmin** [comment]
Thanks!

**Pull request merged**
