### PR TITLE
Arch PKGBUILD

### PR DESCRIPTION
**Pull request by sp1ritCS**
I've create an Arch PKGBUILD (and freedesktop desktop entry)

This should close https://github.com/qarmin/czkawka/issues/35

You can now install czkawka on arch using:
```
yay -S czkawka
```
```
git clone git@github.com:qarmin/czkawka.git && cd czkawka
cd pkgs/arch
makepkg -si
```
or
```
git clone https://aur.archlinux.org/czkawka-git.git && cd czkawka-git
makepkg -si
``` 
---
I've choosen `drive-multidisk` as an icon; feel free to change it

### CODE REVIEW

**Comment by kepet19** [comment]
You are fast! 
That is nice!

**Comment by qarmin** [comment]
What about this comment?
Git dependency should be added?
https://aur.archlinux.org/packages/czkawka-git/#comment-768547

**Comment by sp1ritCS** [comment]
> Oh, I totally forgot that *derp*

**Review by qarmin — APPROVED** [review]

**Comment by qarmin** [comment]
Tested on Manjaro and it works really fine.

**Pull request merged**
