### PR TITLE
Windows implementation of filter_hard_links() function

### PR DESCRIPTION
**Pull request by CalunVier**
Implementation of czkawka_core/src/duplicate.rs filter_hard_links(), with new crate file_id 0.2.1.

Krokiet for Windows has been compiled and tested and works fine. However, due to **Cargo.lock**, Github Action cannot compile the GTK version. I don't have a Rust programming environment on my local machine, so I can't configure it. This part needs the help of the project maintainer.

### CODE REVIEW

**Comment by CalunVier** [comment]
#1267

**Comment by CalunVier** [comment]
My friend helped me update Cargo.lock, but one compilation failed even though there were no errors in the program, and I'm not sure why. It seems that the Github Action timed out.

**Comment by CalunVier** [comment]
> My friend helped me update Cargo.lock, but one compilation failed even though there were no errors in the program, and I'm not sure why. It seems that the Github Action timed out.

Ummmm, it seems like there is something wrong. My friend and I are not very proficient in rust, so I surrender. Before merging, other users can go to my forked action to get the Windows package.

**Comment by qarmin** [comment]
Thanks!

**Pull request merged**
